### ISSUE TITLE
Tiny_RTC Master 

### ISSUE THREAD

**Issue by androg55** [nortxort/pinylib-rtc#5]
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\andre\Desktop\TINYBOT\tinybot-rtc-master -GLCHAT\pinylib.py", line 144, in connect
    self.__callback()
  File "C:\Users\andre\Desktop\TINYBOT\tinybot-rtc-master -GLCHAT\pinylib.py", line 236, in __callback
    self.on_unpublish(json_data['handle'])
  File "C:\Users\andre\Desktop\TINYBOT\tinybot-rtc-master -GLCHAT\pinylib.py", line 549, in on_unpublish
    _user.is_broadcasting = False
AttributeError: 'NoneType' object has no attribute 'is_broadcasting'

**Comment by Technetium1** [comment]
@androg55 This is fixed in #4, with a check for None here: https://github.com/nortxort/pinylib-rtc/commit/8312857a6f408fab50c9bd158c43949f685f930f#diff-78ebb9159d0f2e62a68dd98ab604723eR535
